{{ config(
    materialized='view',
) }}


SELECT 
    unique_key,
    {{ cast_number_clean('"No. Urut"', 'bigint') }} as no_urut,
	{{ cast_string_clean('"Ref"', 'varchar') }} as ref, 
	TO_DATE(trim("Tgl Ref"), 'DD/MM/YYYY') as tgl_referensi,
	{{ cast_string_clean('"No. Ref"', 'varchar') }} as no_referensi, 
	{{ cast_string_clean('"No. Dok Ref"', 'varchar') }} as no_dokumen_referensi, 
	{{ cast_string_clean('"Kode Cust"', 'varchar') }} as kode_konsumen, 
	{{ cast_string_clean('"Nama Cust"', 'varchar', true) }} as nama_konsumen, 
	{{ cast_string_clean('"Alamat Cust"', 'varchar', true) }} as alamat_konsumen, 
	coalesce({{ cast_string_clean('"Kode Panel"', 'varchar') }}, 'OTHER') as kode_panel, 
	coalesce({{ cast_string_clean('"Nama Panel"', 'varchar', true) }}, 'OTHER') as nama_panel, 
	{{ cast_string_clean('"Kode Sales"', 'varchar') }} as kode_sales, 
	{{ cast_string_clean('"Nama Sales"', 'varchar', true) }} as nama_sales, 
	coalesce({{ cast_string_clean('"Keterangan"', 'varchar', true) }},'N/A') as keterangan, 
	{{ cast_string_clean('"Pajak"', 'varchar') }} as pajak, 
	{{ cast_string_clean('"Kategori Pjk"', 'varchar') }} as kategori_pajak, 
	{{ cast_string_clean('"Kode Barang"', 'varchar') }} as kode_barang, 
	coalesce({{ cast_string_clean('"Nama Jns Brg"', 'varchar', true) }}, 'N/A') as nama_jenis_barang, 
	{{ cast_string_clean('"Ket Ref"', 'varchar', true) }} as keterangan_referensi, 
	{{ cast_number_clean('"Qty"', 'int') }} as quantity, 
	{{ cast_string_clean('"Sat"', 'varchar') }} as satuan, 
	{{ cast_number_clean('"Qty Std"', 'int') }} as quantity_standart, 
	{{ cast_string_clean('"Sat Std"', 'varchar') }} as satuan_standart, 
	{{ cast_number_clean('"Harga (+)"', 'numeric(20,4)') }} as harga, 
	{{ cast_number_clean('"Harga Sbl (+)"', 'numeric(20,4)') }} as harga_sebelum, 
	{{ cast_number_clean('"Harga Unit(Mu)"', 'numeric(20,4)') }} as harga_unit, 
	{{ cast_number_clean('"Total(MU)"', 'numeric(20,4)') }} as total, 
	{{ cast_number_clean('"Disc. 1 (%)"', 'numeric(8,4)') }} as diskon_1_persen, 
	{{ cast_number_clean('"Disc. 1 (MU)"', 'numeric(20,4)') }} as diskon_1_amount, 
	{{ cast_number_clean('"Disc. 2 (%)"', 'numeric(8,4)') }} as diskon_2_persen, 
	{{ cast_number_clean('"Disc. 2 (MU)"', 'numeric(20,4)') }} as diskon_2_amount, 
	{{ cast_number_clean('"Disc. 3 (%)"', 'numeric(8,4)') }} as diskon_3_persen, 
	{{ cast_number_clean('"Disc. 3 (MU)"', 'numeric(20,4)') }} as diskon_3_amount, 
	{{ cast_number_clean('"Disc. 4 (MU)"', 'numeric(20,4)') }} as diskon_4_amount, 
	{{ cast_number_clean('"Disc. 5 (%)"', 'numeric(8,4)') }} as diskon_5_persen, 
	{{ cast_number_clean('"Disc. 5 (MU)"', 'numeric(20,4)') }} as diskon_5_amount, 
	{{ cast_number_clean('"Disc. 6 (MU)"', 'numeric(20,4)') }} as diskon_6_amount, 
	{{ cast_number_clean('"Subtot Disc(Mu)"', 'numeric(20,4)') }} as sub_total_diskon_amount, 
	{{ cast_number_clean('"Subtot(Mu)"', 'numeric(20,4)') }} as sub_total_amount, 
	{{ cast_number_clean('"Hrg Unit Riil(Mu)"', 'numeric(20,4)') }} as harga_unit_rill_amount, 
	{{ cast_number_clean('"Total Riil(Mu)"', 'numeric(20,4)') }} as total_riil_amount, 
	{{ cast_number_clean('"Subtot Disc Riil(Mu)"', 'numeric(20,4)') }} as sub_total_diskon_riil_amount, 
	{{ cast_number_clean('"Subtot Riil(Mu)"', 'numeric(20,4)') }} as sub_total_riil_amount, 
	{{ cast_number_clean('"Disc Akh(Mu)"', 'numeric(20,4)') }} as diskon_akhir_amount, 
	{{ cast_number_clean('"Subtot Net(Mu)"', 'numeric(20,4)') }} as sub_total_net_amount, 
	{{ cast_number_clean('"Pjk(Mu)"', 'numeric(20,4)') }} as pajak_amount, 
	{{ cast_number_clean('"Subtot Net Pjk(Mu)"', 'numeric(20,4)') }} as sub_total_net_pajak_amount, 
	coalesce({{ cast_string_clean('"Kode Kota"', 'varchar') }}, 'OTHER') as kode_kota, --cast(trim("Kode Kota") as varchar) as kode_kota,
	coalesce({{ cast_string_clean('"Nama Kota"', 'varchar', true) }}, 'OTHER') as nama_kota, --cast(upper(trim("Nama Kota")) as varchar) as nama_kota,
	load_at
FROM {{ source('raw_layer', 'raw_sales')}}
